# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

workflows:
  test-singularity:
    jobs:
      - build:
          context: dockerhub # has an env var called MY_ENV_VAR

jobs:
  build:
    machine:
      - image: ubuntu-2004:202010-01
    steps:
      - run: |
          docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
          docker run --privileged -v /circle_ci/test_container/:/root/singularity_files singularity build python_app.simg python_app.def
