# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

workflows:
  test-singularity:
    jobs:
      - test:
          context: dockerhub # has an env var called MY_ENV_VAR

jobs:
  test:
    docker:
      - image: roblhall/singularity
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: --help
